# analyze all vhdl filter file
analyze -f vhdl -lib WORK ../multiplier_24bit/src/adder.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/bN_2to1mux.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/bN_3to1mux.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/full_adder.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/half_adder.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/CSA.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/partial_product_generator.vhd
analyze -f vhdl -lib WORK ../multiplier_24bit/src/significant_multiplier.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/common/packfp_packfp.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/common/fpround_fpround.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/common/fpnormalize_fpnormalize.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/common/unpackfp_unpackfp.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/multiplier/fpmul_stage4_struct.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/multiplier/fpmul_stage3_struct.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/multiplier/fpmul_stage2_struct.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/multiplier/fpmul_stage1_struct.vhd
analyze -f vhdl -lib WORK ../fpuvhdl/multiplier/fpmul_pipeline.vhd
